import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import ClientOnly from "./components/ClientOnly";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LogInModal from "./components/modals/LogInModal";
import getCurrentUser from "./actions/currentUser";
import Providers from "./providers";
import RentModal from "./components/modals/RentModal";
import SearchModal from "./components/modals/SearchModal";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by Erik H",
};

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser(); // Fetch the current user--> its not fetchin no idea y!

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${font.className} antialiased`}
      >
        <Providers>
          <ClientOnly>
            <ToasterProvider />
            <RegisterModal />
            <SearchModal />
            <RentModal />
            <LogInModal />
            <Navbar currentUser={currentUser} /> {/* Pass currentUser here */}
          </ClientOnly>
          <div
            className="
          pb-20
          pt-28

          "
          >
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
